/*
  ____                                   _             _       
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __  
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \ 
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/         
# A Template for Forecast_agentPlugin, a Source Plugin
# Generated by the command: plugin -t source -d forecast_agent forecast_agent
# Hostname: alessandroThinkPad
# Current working directory: /home/allegiova/Desktop/FONTANELLI
# Creation date: 2026-03-13T09:49:14.244+0100
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <source.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include "forecast.hpp"
#include <iostream>
#include <chrono>



// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "forecast_agent"
#endif

#define PERIOD 0.001  

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Forecast_agentPlugin : public Source<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    // load the data as necessary and set the fields of the json out variable

    // This sets the agent_id field in the output json object, only when it is
    // not empty

    auto now = std::chrono::steady_clock::now();
    auto dt  = std::chrono::duration_cast<std::chrono::seconds>(now - _last_update).count();
    

    auto now_time_t = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
      tm* local_tm = std::localtime(&now_time_t);
      int current_hour = local_tm->tm_hour - 1;

    try {
      if (dt > _update_interval_sec || !_valid_weather) {  // es. aggiorna ogni 60 s
        _weather = fetchWeather(46.0691, 11.1212, 1);
        _last_update = now;
        _valid_weather = true;
      }
    } catch (const std::exception &e) {
      // logga l’errore e continua usando l’ultimo valore valido
      std::cerr << "fetchWeather error: " << e.what() << std::endl;
    }

    if (_valid_weather) {
      out["wind"] = _weather.wind_speed_10m;
      out["temperature"] = _weather.temperature_2m;
      out["cloud_cover"] = _weather.cloud_cover;
      out["precipitation"] = _weather.precipitation;
      out["direct_normal_irradiance"] = _weather.direct_normal_irradiance;
      out["estimated_flow_m3s"] = _weather.estimated_flow_m3s;
      out["fmu_input"]["actual_wind"] = _weather.wind_speed_10m[current_hour] / 3.6;
    }

    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
      if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }

  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Source::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);
    
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  WeatherData _weather;
  std::chrono::steady_clock::time_point _last_update;
  bool _valid_weather = false;
  int _update_interval_sec = 600;  // configurabile da set_params

};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_SOURCE_DRIVER(Forecast_agentPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  Forecast_agentPlugin plugin;
  json output, params;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.get_output(output);

  // Produce output
  cout << "Output: " << output << endl;

  return 0;
}
